version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/src:/usr/share/nginx/html
    depends_on:
      - frontend
    networks:
      - restaurant-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - restaurant-network

  menu:
    build: ./menu-service
    ports:
      - "5001:5000"
    networks:
      - restaurant-network

  reservations:
    build: ./reservations-service
    ports:
      - "5002:5000"
    environment:
      - FORMSPREE_URL=https://formspree.io/f/xwpqganp
    networks:
      - restaurant-network

  order:
    build: ./order-service
    ports:
      - "5003:5000"
    environment:
      - FORMSPREE_URL=https://formspree.io/f/xwpqganp
    networks:
      - restaurant-network

#   db:
#     image: postgres:13
#     environment:
#       - POSTGRES_DB=restaurant
#       - POSTGRES_USER=admin
#       - POSTGRES_PASSWORD=password
#     volumes:
#       - ./db-service/init.sql:/docker-entrypoint-initdb.d/init.sql
#       - postgres-data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     networks:
#       - restaurant-network

# volumes:
#   postgres-data:

networks:
  restaurant-network:
    driver: bridge
